const fieldMap = [
  { from: 'CHamod', to: 'abilCHA', position: 0 },
  { from: 'STRmod', to: 'abilSTR', position: 0 },
  { from: 'CONmod', to: 'abilCON', position: 0 },
  { from: 'INTmod', to: 'abilINT', position: 0 },
  { from: 'WISmod', to: 'abilWIS', position: 0 },
  { from: 'DEXmod', to: 'abilDEX', position: 0 },
  
  { from: 'CHA', to: 'abilCHA', position: 4 },
  { from: 'STR', to: 'abilSTR', position: 4 },
  { from: 'CON', to: 'abilCON', position: 4 },
  { from: 'INT', to: 'abilINT', position: 4 },
  { from: 'WIS', to: 'abilWIS', position: 4 },
  { from: 'DEX', to: 'abilDEX', position: 4 },
  
  { from: 'ST Charisma', to: 'abilCHA', position: 1 },
  { from: 'ST Strength', to: 'abilSTR', position: 1 },
  { from: 'ST Constitution', to: 'abilCON', position: 1 },
  { from: 'ST Intelligence', to: 'abilINT', position: 1 },
  { from: 'ST Wisdom', to: 'abilWIS', position: 1 },
  { from: 'ST Dexterity', to: 'abilDEX', position: 1 },
  
  { from: 'ChaProf', charCodeAt8226: true, to: 'abilCHA', position: 3 },
  { from: 'StrProf', charCodeAt8226: true, to: 'abilSTR', position: 3 },
  { from: 'ConProf', charCodeAt8226: true, to: 'abilCON', position: 3 },
  { from: 'IntProf', charCodeAt8226: true, to: 'abilINT', position: 3 },
  { from: 'WisProf', charCodeAt8226: true, to: 'abilWIS', position: 3 },
  { from: 'DexProf', charCodeAt8226: true, to: 'abilDEX', position: 3 },
  
  { from: 'Acrobatics',     to: 'skillAcro', position: 0 },
  { from: 'AnimalHandling', to: 'skillAnim', position: 0 },
  { from: 'Arcana',         to: 'skillArca', position: 0 },
  { from: 'Athletics',      to: 'skillAthl', position: 0 },
  { from: 'Deception',      to: 'skillDece', position: 0 },
  { from: 'History',        to: 'skillHist', position: 0 },
  { from: 'Insight',        to: 'skillInsi', position: 0 },
  { from: 'Intimidation',   to: 'skillInti', position: 0 },
  { from: 'Medicine',       to: 'skillMedi', position: 0 },
  { from: 'Nature',         to: 'skillNatu', position: 0 },
  { from: 'Perception',     to: 'skillPerc', position: 0 },
  { from: 'Performance',    to: 'skillPerf', position: 0 },
  { from: 'Persuasion',     to: 'skillPers', position: 0 },
  { from: 'Religion',       to: 'skillReli', position: 0 },
  { from: 'SleightofHand',  to: 'skillSlei', position: 0 },
  { from: 'Stealth',        to: 'skillStea', position: 0 },
  { from: 'Survival',       to: 'skillSurv', position: 0 },
  { from: 'Constitution',   to: 'skillCons', position: 0 },
  
  { from: 'AcrobaticsProf',     to: 'skillAcro', position: 1, ph: true },
  { from: 'AnimalHandlingProf', to: 'skillAnim', position: 1, ph: true },
  { from: 'ArcanaProf',         to: 'skillArca', position: 1, ph: true },
  { from: 'AthleticsProf',      to: 'skillAthl', position: 1, ph: true },
  { from: 'DeceptionProf',      to: 'skillDece', position: 1, ph: true },
  { from: 'HistoryProf',        to: 'skillHist', position: 1, ph: true },
  { from: 'InsightProf',        to: 'skillInsi', position: 1, ph: true },
  { from: 'IntimidationProf',   to: 'skillInti', position: 1, ph: true },
  { from: 'MedicineProf',       to: 'skillMedi', position: 1, ph: true },
  { from: 'NatureProf',         to: 'skillNatu', position: 1, ph: true },
  { from: 'PerceptionProf',     to: 'skillPerc', position: 1, ph: true },
  { from: 'PerformanceProf',    to: 'skillPerf', position: 1, ph: true },
  { from: 'PersuasionProf',     to: 'skillPers', position: 1, ph: true },
  { from: 'ReligionProf',       to: 'skillReli', position: 1, ph: true },
  { from: 'SleightofHandProf',  to: 'skillSlei', position: 1, ph: true },
  { from: 'StealthProf',        to: 'skillStea', position: 1, ph: true },
  { from: 'SurvivalProf',       to: 'skillSurv', position: 1, ph: true },
  { from: 'ConstitutionProf',   to: 'skillCons', position: 1, ph: true },
  
  { from: 'Check Box 12',   to: 'charDDS', bool: true },
  { from: 'Check Box 13',   to: 'charDDS', bool: true },
  { from: 'Check Box 14',   to: 'charDDS', bool: true },
  
  { from: 'Check Box 15',   to: 'charDSF', bool: true },
  { from: 'Check Box 16',   to: 'charDSF', bool: true },
  { from: 'Check Box 17',   to: 'charDSF', bool: true },
  
  { from: 'CharacterName',  to: 'charName' },
  { from: 'CLASS  LEVEL',   to: 'classString' },
  { from: 'ProfBonus',      to: 'profBonus' },
  { from: 'Background',     to: 'charBG' },
  { from: 'RACE',           to: 'charRace' },
  { from: 'Alignment',      to: 'charAlign' },
  
  { from: 'MaxHP',      to: 'charHPmax' },
  { from: 'Passive1',      to: 'charPassive' },
  { from: 'Init',      to: 'charInit' },
  { from: 'Speed',      to: 'charSpeed' },
  { from: 'PersonalityTraits',      to: 'charPerTraits' },
  { from: 'Ideals',      to: 'charIdeals' },
  { from: 'Bonds',      to: 'charBonds' },
  { from: 'Flaws',      to: 'charFlaws' },
  { from: 'ProficienciesLang',      to: 'unformattedProficiencies' },
  
  { from: 'Features and Traits',    to: 'unformattedFeaturesAndTraits' },
  
  { from: 'XP',      to: 'xp' },
  { from: 'CP',      to: 'cp' },
  { from: 'SP',      to: 'sp' },
  { from: 'EP',      to: 'ep' },
  { from: 'GP',      to: 'gp' },
  { from: 'PP',      to: 'pp' },
  { from: 'AdditionalSenses',      to: 'senses' },

]

module.exports = fieldMap
